name: PlayerWatcherPaperMCPlugin
version: '@version@'
main: bk.minecraftplugin.playerWatcherPaperMCPlugin.PlayerWatcherPaperMCPlugin
api-version: '1.21'
#commands:
#  test:
#    description: Just an example command
